name: Unit Tests
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Caches npm dependencies

      - name: Install dependencies
        run: npm ci # Uses package-lock.json for exact versions

      - name: Test
        run: npm run test:unit
